# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 박수's Clapany
email: design.ur.experience@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    "조금이라도 꾸준히"
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://mrclap.github.io'
## Author
author:
  name: '박수'
  # picture: /assets/images/profile/profile.pn twitter_username: jekyllrb
github_username:  mrclap
logo: "/assets/logos/logo.svg"
permalink: pretty

# favicons:
#   16: '/assets/logos/logo@16px.png'
#   32: '/assets/logos/logo@32px.png'
#   96: '/assets/logos/logo@96px.png'
#   120: '/assets/logos/logo@120px.png'
#   144: '/assets/logos/logo@144px.png'
#   180: '/assets/logos/logo@180px.png'
#   512: '/assets/logos/logo@512px.png'
#   1024: '/assets/logos/logo@1024px.png'


# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed

# pagination
paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

# search
search: true

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
